// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgniDRCMtP4xHHLMu2IExk98H6QRSmn7c',
    appId: '1:637228160296:web:1b95461d41d043dec8ac1d',
    messagingSenderId: '637228160296',
    projectId: 'chat-app-be071',
    authDomain: 'chat-app-be071.firebaseapp.com',
    storageBucket: 'chat-app-be071.appspot.com',
    measurementId: 'G-KJ0H27QC6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKzfSSX6a4AlA6ESYdWUu0A8DRjT9GUM',
    appId: '1:637228160296:android:c3f3a1d691c5c85ac8ac1d',
    messagingSenderId: '637228160296',
    projectId: 'chat-app-be071',
    storageBucket: 'chat-app-be071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0Tm8Th-0HVsCzU-Oyu10O5R44oX_9Gs',
    appId: '1:637228160296:ios:bd59cfa29d6efcd3c8ac1d',
    messagingSenderId: '637228160296',
    projectId: 'chat-app-be071',
    storageBucket: 'chat-app-be071.appspot.com',
    iosClientId: '637228160296-uonr1d4f6dcuh6mtc9bud3s5eov3acc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0Tm8Th-0HVsCzU-Oyu10O5R44oX_9Gs',
    appId: '1:637228160296:ios:5ab1a7c032bcee8ac8ac1d',
    messagingSenderId: '637228160296',
    projectId: 'chat-app-be071',
    storageBucket: 'chat-app-be071.appspot.com',
    iosClientId: '637228160296-ofv9rcvhh24j3cou0oomguijit4ji4ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
